export const articles = [
  {
    articleName: "The Baroque in French Architecture",
    authorName: "Jamal Kay",
    contentTag: "Architecture",
    relevantPlace: "France",
    imgSrc: "img/articles/baroque.jpg",
    alt: "the palace of versailles in france",
    publishDate: "February 2021",
  },
  {
    articleName: "Hyper-Modern Bright Lights",
    authorName: "Riku Yamamoto",
    contentTag: "Culture",
    relevantPlace: "Tokyo",
    imgSrc: "img/articles/bright-lights.jpg",
    alt: "neon lights in tokyo",
    publishDate: "May 2021",
  },
  {
    articleName: "The Magic of a Foreign Commute",
    authorName: "Sasha Brown",
    contentTag: "Culture",
    relevantPlace: "Japan",
    imgSrc: "img/articles/commute.jpg",
    alt: "commuters on a japanese subway train",
    publishDate: "June 2021",
  },
  {
    articleName: "What's the Future of Sushi?",
    authorName: "Alice Ito",
    contentTag: "Food",
    relevantPlace: "Japan",
    imgSrc: "img/articles/sushi.jpg",
    alt: "salmon sushi on a plate with chopsticks",
    publishDate: "April 2021",
  },
  {
    articleName: "Paris: Re-Thinking the City of Romance",
    authorName: "Marie Oake",
    contentTag: "Culture",
    relevantPlace: "Paris",
    imgSrc: "img/articles/paris.jpg",
    alt: "a statue of a headless woman in the louvre",
    publishDate: "March 2021",
  },
  {
    articleName: "What we can learn from Petra's caves",
    authorName: "Miles Smith",
    contentTag: "Culture",
    relevantPlace: "Jordan",
    imgSrc: "img/articles/petra.jpg",
    alt: "the pink caves of petra",
    publishDate: "May 2021",
  },
];
