export const articles = [
  {
    articleName: "The Baroque in French Architecture",
    authorName: "Jamal Kay",
    contentTag: "Architecture",
    relevantPlace: "France",
    imgSrc: "img/articles/baroque.jpg",
    imgSrc2: "img/articles/baroque-2.jpg",
    alt: "the palace of versailles in france",
    publishDate: "February 2021",
  },
  {
    articleName: "Hyper-Modern Bright Lights",
    authorName: "Riku Yamamoto",
    contentTag: "Culture",
    relevantPlace: "Tokyo",
    imgSrc: "img/articles/bright-lights.jpg",
    imgSrc2: "img/articles/bright-lights-2.jpg",
    alt: "neon lights in tokyo",
    publishDate: "May 2021",
  },
  {
    articleName: "The Magic of a Foreign Commute",
    authorName: "Sasha Brown",
    contentTag: "Work",
    relevantPlace: "Japan",
    imgSrc: "img/articles/commute.jpg",
    imgSrc2: "img/articles/commute-2.jpg",
    alt: "commuters on a japanese subway train",
    publishDate: "June 2021",
  },
  {
    articleName: "What's the Future of Sushi?",
    authorName: "Alice Ito",
    contentTag: "Food",
    relevantPlace: "Japan",
    imgSrc: "img/articles/sushi.jpg",
    imgSrc2: "img/articles/sushi-2.jpg",
    alt: "salmon sushi on a plate with chopsticks",
    publishDate: "April 2021",
  },
  {
    articleName: "Paris: Re-Thinking the City of Romance",
    authorName: "Marie Oake",
    contentTag: "Culture",
    relevantPlace: "Paris",
    imgSrc: "img/articles/paris.jpg",
    imgSrc2: "img/articles/paris-2.jpg",
    alt: "a statue of a headless woman in the louvre",
    publishDate: "March 2021",
  },
  {
    articleName: "What we can learn from Petra's caves",
    authorName: "Miles Smith",
    contentTag: "Architecture",
    relevantPlace: "Jordan",
    imgSrc: "img/articles/petra.jpg",
    imgSrc2: "img/articles/petra-2.jpg",
    alt: "the pink caves of petra",
    publishDate: "May 2021",
  },
  {
    articleName: "The history of the Morrocan Riad",
    authorName: "Georgia Ali",
    contentTag: "Architecture",
    relevantPlace: "Morroco",
    imgSrc: "img/articles/riad.jpg",
    imgSrc2: "img/articles/riad-2.jpg",
    alt: "a comfortable chair in a moroccan riad",
    publishDate: "September 2020",
  },
  {
    articleName: "Mexico's Rich Culinary History",
    authorName: "Lola Wright",
    contentTag: "Food",
    relevantPlace: "Mexico",
    imgSrc: "img/articles/mexico-1.jpg",
    imgSrc2: "img/articles/mexico-2.jpg",
    alt: "a plate of Mexican food",
    publishDate: "March 2021",
  },
  {
    articleName: "The Great Austrian Outdoors",
    authorName: "Zara Ali",
    contentTag: "Food",
    relevantPlace: "Mexico",
    imgSrc: "img/articles/austria.jpg",
    imgSrc2: "img/articles/austria-2.jpg",
    alt: "overlooking an austrian mountain",
    publishDate: "July 2021",
  },
  {
    articleName: "Travelling India by Train",
    authorName: "Grayson Law",
    contentTag: "Culture",
    relevantPlace: "India",
    imgSrc: "img/articles/india.jpg",
    imgSrc2: "img/articles/india-2.jpg",
    alt: "an older woman sat on a train",
    publishDate: "July 2021",
  },
  {
    articleName: "Exploring Turkey by Air",
    authorName: "Hannah Grace",
    contentTag: "Culture",
    relevantPlace: "Turkey",
    imgSrc: "img/articles/turkey.jpg",
    imgSrc2: "img/articles/turkey-2.jpg",
    alt: "a hot air balloon over a turkish landscape",
    publishDate: "July 2021",
  },
  {
    articleName: "Nature and Buildings Collide",
    authorName: "Otis Davies",
    contentTag: "Architecture",
    relevantPlace: "Cambodia",
    imgSrc: "img/articles/cambodia.jpg",
    imgSrc2: "img/articles/cambodia-2.jpg",
    alt: "Trees growing over Cambodian temples",
    publishDate: "July 2021",
  },
];
